#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "gpio_types.h"
#include "setup.h"

void setupFPU(void)
{
	SCB->CPACR |= (0b1111 << 20);
	__asm volatile("dsb");
	__asm volatile("isb");
}

void setUpDisplaySegment(void)
{

	GPIOC->MODER &= ~(GPIO_MODER_MODER7);
	GPIOA->MODER &= ~(GPIO_MODER_MODER8) | (GPIO_MODER_MODER9);
	GPIOB->MODER &= ~(GPIO_MODER_MODER10);

	GPIOC->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER7_Pos);
	GPIOA->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER8_Pos) | (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER9_Pos);
	GPIOB->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER10_Pos);

	GPIOC->OTYPER &= ~GPIO_OTYPER_OT7;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT8 | GPIO_OTYPER_OT9);
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT10);
}

void setupButton(void)
{

	GPIO_Button_Init(GPIOA, 10, MY_GPIO_PULL_UP);
	GPIO_Button_Init(GPIOB, 3, MY_GPIO_PULL_UP);
	GPIO_Button_Init(GPIOB, 5, MY_GPIO_PULL_UP);
	GPIO_Button_Init(GPIOB, 4, MY_GPIO_PULL_UP);
	setUpDisplaySegment();
}

void setupClock(void)
{

	RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOAEN + RCC_AHB1ENR_GPIOBEN + RCC_AHB1ENR_GPIOCEN);
	RCC->APB2ENR |= (RCC_APB2ENR_SYSCFGEN + RCC_APB2ENR_ADC1EN);
	RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
}

void setupLED(void)
{

	GPIOA->MODER &= ~(GPIO_MODER_MODER5 | GPIO_MODER_MODER6 | GPIO_MODER_MODER7);
	GPIOB->MODER &= ~(GPIO_MODER_MODER6);

	GPIOA->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER5_Pos) | (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER6_Pos) | (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER7_Pos);
	GPIOB->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER6_Pos);
}

void setupAnalog(void)
{

	// Setup Temperature Sensor
	GPIOA->MODER &= ~(GPIO_MODER_MODER0);
	GPIOA->MODER |= (MY_GPIO_MODE_ANALOG << GPIO_MODER_MODER0_Pos);
}

void setupTemperature(void)
{

	ADC1->CR2 |= ADC_CR2_ADON;
	ADC1->SMPR2 |= ADC_SMPR2_SMP0;
	ADC1->SQR1 &= ~(ADC_SQR1_L);
	ADC1->SQR1 |= (1 << ADC_SQR1_L_Pos);
	ADC1->SQR3 &= ~(ADC_SQR3_SQ1);
	ADC1->SQR3 |= (0 << ADC_SQR3_SQ1_Pos);

	setupFPU();
}

void setupOLED(void)
{

	GPIO_Button_Init(GPIOB, 6, MY_GPIO_PULL_UP);
	GPIO_Button_Init(GPIOB, 7, MY_GPIO_PULL_UP);
}