#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "gpio_types.h"
#include "setup.h"

void setUpDisplaySegment(void)
{

	GPIOC->MODER &= ~(GPIO_MODER_MODER7);
	GPIOA->MODER &= ~(GPIO_MODER_MODER8) | (GPIO_MODER_MODER9);
	GPIOB->MODER &= ~(GPIO_MODER_MODER10);

	GPIOC->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER7_Pos);
	GPIOA->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER8_Pos) | (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER9_Pos);
	GPIOB->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER10_Pos);

	GPIOC->OTYPER &= ~GPIO_OTYPER_OT7;
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT8 | GPIO_OTYPER_OT9);
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT10);
}

void setupButton(void)
{

	GPIO_Button_Init(GPIOA, 10, MY_GPIO_PULL_UP);
	GPIO_Button_Init(GPIOB, 3, MY_GPIO_PULL_UP);
	GPIO_Button_Init(GPIOB, 5, MY_GPIO_PULL_UP);
	GPIO_Button_Init(GPIOB, 4, MY_GPIO_PULL_UP);
	setUpDisplaySegment();
}

void setupClock(void)
{

	RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOAEN + RCC_AHB1ENR_GPIOBEN + RCC_AHB1ENR_GPIOCEN);
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
}

void setupLED(void)
{

	GPIOA->MODER &= ~(GPIO_MODER_MODER5 | GPIO_MODER_MODER6 | GPIO_MODER_MODER7);
	GPIOB->MODER &= ~(GPIO_MODER_MODER6);

	GPIOA->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER5_Pos) | (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER6_Pos) | (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER7_Pos);
	GPIOB->MODER |= (MY_GPIO_MODE_OUTPUT << GPIO_MODER_MODER6_Pos);
	
}